### ISSUE TITLE
notebooks/run_models_on_chime.ipynb results are different.

### ISSUE THREAD

**Issue by rimiyeyo** [etzinis/unsup_speech_enh_adaptation#4]
Hi! I have a question.
In notebooks/run_models_on_chime.ipynb, Reproduction is not the same!
If data is extracted with '`python create_audio_segments.py {insert_path_of_CHiME5_data} json_files {insert_path_of_processed_10s_CHiME5_data} --train_10s`', only the dev folder and train folder are extracted, so the dev folder is used instead of the eval folder. I used ckpt in the pretrained_checkpoints folder. However, the result comes out differently.

![image](https://user-images.githubusercontent.com/18730383/222381691-4c6c2d30-b7aa-4225-a405-b319f0abb62a.png)

The sound source should be separated, but it doesn't seem to be separated at all. Can you tell me what's the problem?

Thanks..

**Comment by etzinis** [comment]
This notebook, was intended to serve for debug purposes - probably I should simply delete it. I do not know what do you mean exactly by reproduction problem here, probably the problem comes in cause you are using a model trained with mixture consistency and you don't apply mixture consistency at the end. I have an example in the same file on how to use a model trained with mixture consistency.

```
rec_sources_wavs = w_mix_con_model(input_mix)
rec_sources_wavs = mixture_consistency.apply(rec_sources_wavs, input_mix)
```

**Comment by rimiyeyo** [comment]
thank you! 
Solved by adding `rec_sources_wavs = mixture_consistency.apply(rec_sources_wavs, input_mix)` source!
